### ISSUE TITLE
Disable all non-time Statistics by default

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/bdd-benchmark#54]
Even if one does not compile with statistics, one still calls the `nodecount` function after each operation. This still (if not much) has an impact on the running time.

**Tasks**

- [x] Wrap the `adapter.nodecount(...)` function calls within the `#ifdef BDD_BENCHMARK_STATS` preprocessor flag. 
- [x] Hide printing the generated data with a preprocessor flag.

**Benchmarks**

- [x] *queens*
- [x] *tic-tac-toe*
- [x] *picotrav*

**Comment by SSoelvsten** [comment]
Closed with c1453b0
